# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GcdModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left', models.IntegerField()),
                ('right', models.IntegerField()),
                ('ans', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='PrimeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.IntegerField()),
                ('ans', models.CharField(max_length=1000)),
            ],
        ),
    ]
